# Generated by Django 5.2.4 on 2025-07-23 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Plan Pilates Mensual', max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuencia', models.CharField(choices=[('Semanal', 'Semanal'), ('Mensual', 'Mensual')], max_length=10)),
                ('sesiones_por_periodo', models.PositiveIntegerField(help_text='¿Cuántas clases puede tomar por semana/mes?')),
                ('servicios', models.ManyToManyField(help_text='¿Qué servicios incluye este plan?', to='gestion.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('sesiones_usadas', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.plan')),
            ],
        ),
    ]
