# Generated by Django 5.2.4 on 2025-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_plan_clienteplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='porcentaje_dueño',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje del precio de venta que corresponde al dueño.', max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='porcentaje_dueño',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje del precio de venta que corresponde al dueño.', max_digits=5),
        ),
    ]
