# Generated by Django 5.2.4 on 2025-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_abono_porcentaje_dueño_plan_porcentaje_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudaempleado',
            name='concepto_adicional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
